name: Atualizar Lista M3U

on:
  schedule:
    - cron: '0 12 * * *'   # 09h em Brasília
    - cron: '0 15 * * *'   # 12h em Brasília
  workflow_dispatch:        # Execução manual

jobs:
  atualizar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Baixar lista M3U original
        run: |
          LINK=$(cat link_m3u.txt)
          curl -L "$LINK" -o listaETflix.m3u

      - name: Commit e push se houver mudanças
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add listaETflix.m3u
          if git diff --cached --quiet; then
            echo "Sem mudanças, não precisa commitar."
          else
            git commit -m "Atualização automática da lista M3U original"
            git push
          fi
