name: Atualizar Lista M3U

on:
  schedule:
    - cron: '0 3 * * *'  # Executa todos os dias às 03:00 UTC (00:00 no Brasil)
  workflow_dispatch:

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Baixar nova lista M3U
        run: |
          curl -o listaETflix.m3u "http://invictosplay.pro/get.php?username=692414414236&password=657211278483&type=m3u_plus&output=mpegts"

      - name: Commit e push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add listaETflix.m3u
          git commit -m "Atualização automática da lista M3U"
          git push
